### ISSUE TITLE
cant move objects in the decorator & maybe add interactable objects like stash so you can store items

### ISSUE THREAD

**Issue by BlackBullGames** [borisnliscool/bnl-housing#12] opened 2023-03-28 09:30 UTC
when i am in the decorator i cant move the items around idk why or if this is normal but it wont move the items

and maybe add a stash that stores items with a customizable max weight for the items

**Comment by borisnliscool** [comment] 2023-03-28 10:13
Hello BlackBullGames,

Thank you for reporting the issue with moving items around within the decorator. However, I wanted to let you know that the script you mentioned has not yet been released, so it may not be possible to move items around within the decorator as intended.

Regarding your suggestion to add a stash with customizable max weight, it looks like special props can be used for this purpose. You can refer to this link for more information: https://github.com/borisnliscool/bnl-housing/blob/main/data/specialprops.lua.

If you have any more specific details or code snippets related to the issue you're facing, please feel free to share them so that we can provide a more accurate response.

Thank you for your understanding.

Best regards,
Boris

**Comment by BlackBullGames** [comment] 2023-03-28 11:11
ofcourse i understand that it has not been released yet Xd i just wanted to let you know it wasnt working yet incase you didnt know it Xd
since its in development 
i do love the script since it has car storage optionality

**Closed** 2023-06-30 22:34 UTC
